import { StyleSheet } from "react-native";
import { Colors } from "@/constants/Colors";

export const createStyles = (theme, isLandscape) => {
  return StyleSheet.create({
    container: {
      flexGrow: 1,
      backgroundColor: "#e4d7c2",
    },
    backgroundContainer: {
      height: 180,
      width: "100%",
      position: "relative",
    },
    svg: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    headerContent: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 180,
      justifyContent: "center",
      alignItems: "center",
      paddingTop: 20,
    },
    headerImage: {
      width: "80%",
      height: 120,
      marginBottom: 20,
    },
    card: {
      backgroundColor: "white",
      borderRadius: 20,
      padding: 20,
      width: "90%",
      marginTop: 300,
      alignSelf: "center",
      marginBottom: 50,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      alignItems: "center",
      elevation: 3,
    },
    cardLandscape: {
      width: "100%",
      maxWidth: 650,
      backgroundColor: "white",
      borderRadius: 20,
      padding: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      alignItems: "center",
    },
    title: {
      fontSize: 52,
      fontWeight: "300",
      color: theme.pink,
      marginBottom: 20,
      textAlign: "center",
    },
    landscapeContainer: {
      flex: 1,
      flexDirection: "row",
      width: "90%",
      maxWidth: 1300,
      alignSelf: "center",
      backgroundColor: "#ffffff",
      borderRadius: 27,
      overflow: "hidden",
      elevation: 3,
      height: "80%",
      marginVertical: 40,
    },
    leftSide: {
      width: "50%",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#FFFFFF",
      padding: 20,
    },
    rightSide: {
      width: "50%",
      justifyContent: "center",
      alignItems: "center",
      padding: 30,
      backgroundColor: "#ffffff",
    },
    svgBackground: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: "100%",
      zIndex: -1,
      width: 1000,
      marginTop: "-5%",
      marginLeft: "-40%",
    },
    image: {
      width: "90%",
      height: "60%",
      marginTop: 40,
    },
  });
};